# Generated by Django 4.1.1 on 2022-10-14 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity', models.FloatField()),
                ('ingrident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recepie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingridents', models.ManyToManyField(through='kitchen.Quantity', to='kitchen.ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='quantity',
            name='recepie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kitchen.recepie'),
        ),
    ]
