# Generated by Django 4.1.1 on 2022-10-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='ingrident',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='recepie',
            old_name='ingridents',
            new_name='ingredients',
        ),
    ]
