# Generated by Django 4.1.1 on 2022-10-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_rename_ingrident_quantity_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
